import { MolecularStructure } from './molecularData.js';

export function generatePDB(molecule: MolecularStructure): string {
    const lines: string[] = [];
    lines.push('REMARK   Generated by NanoVer Builder WebXR');

    for (const atom of molecule.atoms) {
        const serial = (atom.index + 1).toString().padStart(5);
        const name = atom.element.padEnd(4);
        // nm -> angstroms
        const x = (atom.position.x * 10).toFixed(3).padStart(8);
        const y = (atom.position.y * 10).toFixed(3).padStart(8);
        const z = (atom.position.z * 10).toFixed(3).padStart(8);
        const element = atom.element.padStart(2);
        lines.push(
            `HETATM${serial} ${name} UNL     1    ${x}${y}${z}  1.00  0.00          ${element}`
        );
    }

    for (const bond of molecule.bonds) {
        const a = (bond.a.index + 1).toString().padStart(5);
        const b = (bond.b.index + 1).toString().padStart(5);
        lines.push(`CONECT${a}${b}`);
        lines.push(`CONECT${b}${a}`);
    }

    lines.push('END');
    return lines.join('\n');
}

/** Download PDB as a file via the browser. */
export function downloadPDB(molecule: MolecularStructure, filename = 'molecule.pdb') {
    const pdbText = generatePDB(molecule);
    const blob = new Blob([pdbText], { type: 'chemical/x-pdb' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}
